image: Visual Studio 2015 - GCE

install:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-http-proxy.ps1'))
  - cinst pester
  #- ps: Invoke-WebRequest -Uri 'http://sdk-for-net.amazonwebservices.com/latest/AWSToolsAndSDKForNet.msi' -UseBasicParsing -OutFile 'AWSToolsAndSDKForNet.msi'
  - Write-Host "PSModulePath: $env:PSModulePath"
  - appveyor DownloadFile http://sdk-for-net.amazonwebservices.com/latest/AWSToolsAndSDKForNet.msi
  - ps: msiexec.exe /i AWSToolsAndSDKForNet.msi /quiet /qn /norestart /log install.log
  - Write-Host "PSModulePath: $env:PSModulePath"

build: false

test_script:
  - ps: Import-Module AWSPowershell
  - ps: $res = Invoke-Pester -Path ".\Tests" -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}
